### ISSUE TITLE
Custom feature row does not show up in new Area Card (2025.7)

### ISSUE THREAD

**Issue by bhessen** [Nerwyn/custom-card-features#124]
**Checklist:**

- [ x] I updated to the latest version available
- [x ] I cleared the cache of my browser
- [ ] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**

**Last working release (if known):**
2025.7 and 4.5.0 of Integration
**Browser and Operating System:**
Android ha companion app

**Description of problem:**

With 2025.7 HA extended the capabilities of the standard area card with Card Features similar to the tile Card. The custom feature row shows up in the dialog as an option and it can be added and edited normally.
But the result is that the card gets 1 row bigger but the custom feature row is Not showing up.
Instead the area Icon/picture gets bigger

**Javascript errors shown in the web inspector (if applicable):**

```
None
```

**Your Full Card Config**

```yaml
features:
  - type: area-controls
    controls:
      - light
      - cover-shutter
  - type: custom:service-call
    entries:
      - type: button
        entity_id: sensor.netatmo_wohnzimmer_noise
        label: "{{ value | float }}"
        icon: mdi:molecule-co2
alert_classes:
  - motion
  - moisture
  - window
sensor_classes:
  - temperature
  - humidity
features_position: bottom
display_type: icon
type: area
color: teal
area: wohnzimmer
grid_options:
  columns: 6
  rows: 4

```

**Additional information:**

**Comment by Kvasenok** [comment]
I can confirm. I have the exact same behavior with the new area card.

**Comment by Nerwyn** [comment]
I can also confirm. ~Unfortunately, this seems to be a bug with Home Assistant not properly rendering custom features within area card.~

![Image](https://github.com/user-attachments/assets/4c3897e7-cccf-42ae-9929-17cbbd56945b)

I'm going to dig into the Home Assistant frontend code to find the root cause and create a bug there if I can find the issue.

**Comment by Nerwyn** [comment]
Figured it out. Area cards do not have entity IDs, which are required for the state object that is normally passed to card features for them to know which entity to act on. I should be able to just disable the state object required check in this project to fix it, but I need to make sure that that doesn't break everything else.

**Comment by Nerwyn** [comment]
Fixed in [4.5.1](https://github.com/Nerwyn/custom-card-features/releases/tag/4.5.1)!

![Image](https://github.com/user-attachments/assets/f70c2eae-7e4c-48fd-9170-7e286515ca50)

**Comment by bhessen** [comment]
Sadly, this is not working for me.

With 4.5.1 I now have the option 'custom feature row' twice. But the behaviour is still the same as before.

**Comment by Nerwyn** [comment]
It sounds like you have a bad install. [There's nothing between 4.5.0 and 4.5.1 that would cause that](https://github.com/Nerwyn/custom-card-features/compare/4.5.0...4.5.1), nor anything between 4.5.0 and the last minor-patch version. Make sure that you don't have any old installations in your [frontend resources list](http://homeassistant.local:8123/config/lovelace/resources) or an old install in `config/www/community` using an old name like `service-call-tile-feature`.

**Comment by bhessen** [comment]
Thanks. Don't know how, but that was the issue.

**Comment by amitkeret** [comment]
Unfortunately, this is still a problem in version 4.6.9.
HA version 2025.10.1
See below cards. The top is an area card, while the bottom is a tile card. Both have a single row of custom feature/s.
Changing the area card's `display_type` (compact/icon/picture) or `features_position` (bottom/inline) makes no difference.

In the browser:
![image](https://github.com/user-attachments/assets/a36b24bc-a668-4543-9deb-0c10acc26de8)

Android HA companion:
![Image](https://github.com/user-attachments/assets/df02c6d8-2557-4bac-95d5-72672f590970)

**Comment by Nerwyn** [comment]
[Clear your app cache](https://github.com/Nerwyn/material-you-utilities/discussions/12). The only reason why it would not work on different browsers or apps is a caching issue.

**Comment by amitkeret** [comment]
You are indeed correct 👍 

Follow-up questions:
- Have you identified why this module is more affected by this problem than others? Meaning- when I upgrade other HACS modules, I don't run into caching issues. This is the first time I had to clear app cache like this, despite having multiple other modules constantly receiving version updates
- Suggestion- add this like to somewhere (prominent) in the readme for other people who are likely running into this problem

Thank you!

**Comment by Nerwyn** [comment]
The repo and module as renamed for v4 (service-call-tile-feature -> custom-card-features), which caused some issues for people if HACS did not remove the old version. That has caused some installation users for people. Other than that I'm not sure. There's already a pinned issue #110.
